# https://nextjs.org/docs/basic-features/eslint#recommended-plugin-ruleset
env:
  node: true
  es2022: true
  browser: true
extends:
  - eslint:recommended
  - next/core-web-vitals
  - prettier
ignorePatterns:
  - next.config.mjs
rules:
  import/no-anonymous-default-export:
    - warn
    - allowArrowFunction: true
