# https://nextjs.org/docs/basic-features/eslint#recommended-plugin-ruleset
root: true
env: { node: true, es2022: true, browser: true }
extends: [next/core-web-vitals, prettier]
rules:
  import/no-anonymous-default-export:
    [warn, { allowObject: true, allowArrowFunction: true }]
