# https://prettier.io/docs/en/options.html
singleQuote: true

# https://github.com/trivago/prettier-plugin-sort-imports
importOrderSortSpecifiers: true
importOrderGroupNamespaceSpecifiers: true
importOrder:
  - '^(.*)[.]css$'
  - '^(.*)[.]scss$'
  - '^type-fest([/].*)?$'
  - '^(.*)types(.*)$'
  - '^next([/].*)?$'
  - '^react$'
  - '^react-dom$'
  - '<THIRD_PARTY_MODULES>'
  - '^@[/](.*)$'
  - '^[.][/](.*)$'
